### ISSUE TITLE
E011 new board cannot be flash

### ISSUE THREAD

**Issue by zonners** [silver13/Eachine-E011#11]
Hi silver13, do you already know about E011 new board that now replacing all E011 quad? I've got a new board 2 weeks ago, trying to flash, but cannot do the flashing. Afraid that developer block this new board to be flashed. Hope that you can find how to solve this.

Thanks

**Comment by silver13** [comment]
hi, sorry for late reply, I must have missed this post, the new board can't be flashed, try a boldclash board, unfortunately this is common practice in china to just use what they can get cheaply, same thing happened to the original h8 board a few years back
