### ISSUE TITLE
Q: why different file sizes for HEX binary?

### ISSUE THREAD

**Issue by nitram509** [silver13/Eachine-E011#2]
Hi,

first, thank you very much for this great project 👍 

I've build a bwhoop.hex file with gcc (using Travis-CI), but to my surprise, the final .HEX file is 43kByte, instead of 33kByte you provide in bin folder.
Any idea, why there is such a huge difference? (and yes, my compiled version flies ;-) )

Background information:
I've forked it and using now Travis-CI as build agent (see my changes in travis.yml to automatically export .hex file).

Output
```
arm-none-eabi-size bwhoop.elf
   text	   data	    bss	    dec	    hex	filename
  15236	    128	   2832	  18196	   4714	bwhoop.elf
arm-none-eabi-objcopy -O binary bwhoop.elf bwhoop
arm-none-eabi-objcopy -O ihex bwhoop.elf bwhoop.hex
```

Regards
Martin

**Comment by silver13** [comment]
yes, gcc will compile a file size about 40% larger compared to keil, it will also be slower

the gcc fork for cortex is maintained by arm employees I think, and keil is arm's commercial software, I suppose they made it this way

**Comment by nitram509** [comment]
Hi,

thank you for this explanation.
I thought i has to do with e.g. debug symbols are not stripped (did not checked this yet).

What a pity, I found this gcc approach really charming, because of the sleek automation. I even thought about extending the Makefile, to build multiple firmwares in one run and upload them to GitHub - you know, similar like Betaflight is doing. This would ease development very much and give also users a great reliable source for download.
(I mean, using GitHub releases is more convenient and transparent to users and additionally leaves developers freedom to develop on master branch. Release also can contain a release note.)
