### ISSUE TITLE
Question: how is RX buffer updated?

### ISSUE THREAD

**Issue by nitram509** [silver13/Eachine-E011#3]
Hi, 

I'm trying to implement some "comfort" feature like I'm used to from my bigger drones.
May I ask you to explain the core concept of how rx[] buffer and main control loop interacts?

Background:
I would like to switch LEVEL vs. ACRO mode via MODE switch at my DEVO 7e.
Additionally, I would like to make an option for "ARMING" in ACRO mode, which includes motor spinning when idle.

My first humble approach looks like this
https://github.com/nitram509/Eachine-E011/commit/dad26bd8a07ac0e75058b53d159df013cc8037a0

In Keil uVision Debugger I've figured out, that when I switch my radio knob and hit the breakpoint at line
156: if (aux[CH_FLIP] && rx[THROTTLE] < 0.05f) ...
... the rx[THROTTLE] value is 0.0 - even if my radio is full throttle.

This line should prevent ARMING, when full throttle.
But unfortunately, in real life, drone is armed even with full throttle :/
I'm puzzled, how can this happen?

Any help is appreciated.

Regards
Martin

**Comment by silver13** [comment]
the rx buffer gets updated by the radio code when data from tx is received, also throttle gets set to zero on failsafe

I think the problem is you are setting rx[3] to zero in some cases, but the rx does not receive data every loop, so next loop rx[3] = 0 ; hence the arm will activate

best to set the local throttle variable instead

**Comment by nitram509** [comment]
Thank you very much for this hint. 👍 
This makes totally sense to me.

So the only responsibility of writing to the rx[] buffer should really be limited to within the receiver code ("rx*.c" files).
